name: 'Get random ttl.sh image uri and tags'
description: 'Generate random ttl.sh image uri and get tags from `builer-<tag>.toml` files'

inputs:
  folder:
    description:  'The folder containing builder toml files in the form of `builder-<tag>.toml`'
    required:     true

outputs:
  tags:
    description: "Space separated builder tags derived from `builder-<tag>.toml` in given folder"
    value: ${{ steps.workflow-setup.outputs.tags }}
  uri:
    description: "randome generated tags"
    value: ${{ steps.workflow-setup.outputs.uri }}

runs:
  using: "composite"
  steps:
    - id: workflow-setup
      shell: bash
      run: |
        cd ${{ inputs.folder }}
        tags=$(ls *.toml | xargs -n1 | cut -d- -f2 | cut -d. -f1)

        echo "tags=\\\"$tags\\\"" >> $GITHUB_OUTPUT
        echo "uri=ttl.sh/${{ github.repository }}/$(cat /proc/sys/kernel/random/uuid)" >> $GITHUB_OUTPUT