name:        'Create architecture-specific builders'
description: 'Install the Cloud Native Buildpacks pack CLI and add it to $PATH'
author:      'Jerico Pena'

inputs:
  tags:
    description:  'Space-separated list of tags'
    required:     true
  base-image-uri:
    description:  'The base image uri (registry-url/repo-name)'
    required:     true
  publish:
    description:  'Set to `true` to have pack publish to the registry or `false` to save builders to the docker daemon'
    required:     false
    default:      'true'

outputs:
  tags:
    description: "Image tags minus architecture such as `latest` rather than `latest-amd64`"
    value: ${{ steps.image-uri-generator.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Create multi-arch builders
      shell: bash
      run: |
        #!/usr/bin/env bash -euo pipefail

        if [ "${{ inputs.publish }}" = "true" ]; then
          PUBLISH="true"
        else
          PUBLISH=""
        fi
        
        set -x
        for tag in ${{ inputs.tags }}; do
          image_tag="${{ inputs.base-image-uri }}:${tag}"
          docker buildx imagetools create -t "${image_tag}" "${image_tag}-arm64" "${image_tag}-amd64" --dry-run
          if [ ! -z "$PUBLISH" ]; then
            docker buildx imagetools create -t "${image_tag}" "${image_tag}-arm64" "${image_tag}-amd64"
            docker buildx imagetools inspect "${image_tag}"
          fi
        done
    # Test multi-arch builders from amd64
    - if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
      uses: ./.github/actions/multi-arch-builder-test
  