name: jammy build and release
on:
  push:
    branches:
      - "main"
env:
  JAMMY_BASE_IMAGE_URI: 'ghcr.io/jericop/builder-jammy'
  DOCKER_CLI_EXPERIMENTAL: 'enabled'
jobs:
  create-multi-arch-builders:
    runs-on: ubuntu-22.04
    needs: create-arch-builders-matrix
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: jericop/github-actions/buildpacks/create-multi-arch-builders@v1.0.1
        with:
          path: 'jammy'
          base-image-uri: ${{ env.JAMMY_BASE_IMAGE_URI }}
          lifecycle-version: 'v0.16.3'
